import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

// Usage: bun scripts/charmed-icons.ts <path to a clone of github.com/littensy/charmed-icons>
if (!process.argv[2]) throw new Error('Pass the path to a Charmed Icons clone.')
const source = resolve(process.argv[2])
const destination = resolve('src/components/custom/charmed_icons.ts')
const cssDestination = resolve('src/components/custom/charmed_icons.css')
const foldersDestination = resolve('src/components/custom/charmed_folders.ts')

type IconDefinition = { names?: string[]; extensions?: string[] }
const { fileIcons } = (await import(
  pathToFileURL(join(source, 'src/defaults/file-icons.ts')).href
)) as { fileIcons: Record<string, IconDefinition> }
const { basePalette, lightPalette, softPalette } = (await import(
  pathToFileURL(join(source, 'scripts/palettes.ts')).href
)) as {
  basePalette: Record<string, string>
  lightPalette: Record<string, string>
  softPalette: Record<string, string>
}

const { folderNames } = (await import(
  pathToFileURL(join(source, 'src/defaults/folder-icons.ts')).href
)) as { folderNames: Record<string, string> }

const isFolder = (filename: string) =>
  filename.startsWith('folder') || filename.startsWith('_folder')
const svgs = (await readdir(join(source, 'icons')))
  .filter((filename) => filename.endsWith('.svg'))
  .sort()
const filenames = svgs.filter((filename) => !isFolder(filename))
const folderFilenames = svgs.filter(isFolder)
const iconNames = new Set(filenames.map((filename) => filename.slice(0, -4)))
const colors = new Map<string, string>()
// Match generate.ts: when palette keys share a base hex, its first key wins.
for (const [key, value] of Object.entries(basePalette))
  if (!colors.has(value.toLowerCase())) colors.set(value.toLowerCase(), key)
async function symbol(filename: string) {
  const name = filename.slice(0, -4)
  const svg = await readFile(join(source, 'icons', filename), 'utf8')
  if (!/<svg\b[^>]*viewBox="0 0 16 16"/.test(svg))
    throw new Error(`Unexpected viewBox: ${filename}`)
  const body = svg
    .replace(/^<svg\b[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/#[0-9a-f]{6}\b/gi, (hex) => {
      const key = colors.get(hex.toLowerCase())
      return key ? `var(--ci-${key})` : hex
    })
    .replace(/>\s+</g, '><')
    .trim()
  // Every icon's root <svg> sets fill="none"; unfilled strokes rely on it.
  return `<symbol id="ci-${name}" viewBox="0 0 16 16" fill="none">${body}</symbol>`
}
const symbols = await Promise.all(filenames.map(symbol))
const folderSymbols = Object.fromEntries(
  await Promise.all(
    folderFilenames.map(async (filename) => [filename.slice(0, -4), await symbol(filename)])
  )
)
const folders: Record<string, string> = {}
for (const [name, icon] of Object.entries(folderNames)) {
  if (!folderSymbols[icon] || !folderSymbols[`${icon}_open`])
    throw new Error(`Missing folder icon: ${icon}`)
  folders[name.toLowerCase()] = icon
}

const names: Record<string, string> = {}
const extensions: Record<string, string> = {}
for (const [icon, definition] of Object.entries(fileIcons)) {
  if (!iconNames.has(icon)) throw new Error(`Missing file icon: ${icon}`)
  for (const name of definition.names ?? []) names[name.toLowerCase()] = icon
  for (const extension of definition.extensions ?? []) extensions[extension.toLowerCase()] = icon
}

const license = (await readFile(join(source, 'LICENSE.md'), 'utf8'))
  .trim()
  .split('\n')
  .map((line) => ` * ${line}`)
  .join('\n')
const output = `/*\n${license}\n */\n\n// Generated by scripts/charmed-icons.ts from Charmed Icons.\nexport const charmedSprite = ${JSON.stringify(symbols.join(''))};\n\nexport const charmedFileNames: Record<string, string> = ${JSON.stringify(names, null, 2)};\n\nexport const charmedExtensions: Record<string, string> = ${JSON.stringify(extensions, null, 2)};\n`
await writeFile(destination, output)
// Folders are a module of their own: a tree takes only the symbols for the folders it shows.
await writeFile(
  foldersDestination,
  `/*\n${license}\n */\n\n// Generated by scripts/charmed-icons.ts from Charmed Icons. Each icon has an "_open" twin.\nexport const charmedFolderSymbols: Record<string, string> = ${JSON.stringify(folderSymbols, null, 2)};\n\nexport const charmedFolderNames: Record<string, string> = ${JSON.stringify(folders, null, 2)};\n`
)
const variables = (palette: Record<string, string>) =>
  Object.entries(palette)
    .map(([key, value]) => `  --ci-${key}: ${value};`)
    .join('\n')
await writeFile(
  cssDestination,
  `/* Generated from Charmed Icons palettes by scripts/charmed-icons.ts. */\n[data-charmed] {\n${variables(basePalette)}\n}\n\n.dark [data-charmed="soft"] {\n${variables(softPalette)}\n}\n\n:root:not(.dark) [data-charmed] {\n${variables(lightPalette)}\n}\n`
)
console.log(
  `Wrote ${filenames.length} file symbols, ${folderFilenames.length} folder symbols and palette CSS`
)
