/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as BotsBotIdRouteImport } from './routes/bots.$botId'
import { Route as DevFeelsRouteImport } from './routes/dev.feels'
import { Route as PullRequestsIndexRouteImport } from './routes/pull-requests.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsPageRouteImport } from './routes/settings.$page'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads.$threadId'
import { Route as PullRequestsOwnerRepoNumberRouteImport } from './routes/pull-requests.$owner.$repo.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFeelsRoute = DevFeelsRouteImport.update({
  id: '/dev/feels',
  path: '/dev/feels',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsIndexRoute = PullRequestsIndexRouteImport.update({
  id: '/pull-requests/',
  path: '/pull-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPageRoute = SettingsPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => SettingsRoute,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsOwnerRepoNumberRoute =
  PullRequestsOwnerRepoNumberRouteImport.update({
    id: '/pull-requests/$owner/$repo/$number',
    path: '/pull-requests/$owner/$repo/$number',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/dev/feels': typeof DevFeelsRoute
  '/settings/$page': typeof SettingsPageRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/pull-requests/': typeof PullRequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/pull-requests/$owner/$repo/$number': typeof PullRequestsOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/usage': typeof UsageRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/dev/feels': typeof DevFeelsRoute
  '/settings/$page': typeof SettingsPageRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/pull-requests': typeof PullRequestsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/pull-requests/$owner/$repo/$number': typeof PullRequestsOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/dev/feels': typeof DevFeelsRoute
  '/settings/$page': typeof SettingsPageRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/pull-requests/': typeof PullRequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/pull-requests/$owner/$repo/$number': typeof PullRequestsOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/usage'
    | '/bots/$botId'
    | '/dev/feels'
    | '/settings/$page'
    | '/threads/$threadId'
    | '/pull-requests/'
    | '/settings/'
    | '/pull-requests/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/usage'
    | '/bots/$botId'
    | '/dev/feels'
    | '/settings/$page'
    | '/threads/$threadId'
    | '/pull-requests'
    | '/settings'
    | '/pull-requests/$owner/$repo/$number'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/usage'
    | '/bots/$botId'
    | '/dev/feels'
    | '/settings/$page'
    | '/threads/$threadId'
    | '/pull-requests/'
    | '/settings/'
    | '/pull-requests/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UsageRoute: typeof UsageRoute
  BotsBotIdRoute: typeof BotsBotIdRoute
  DevFeelsRoute: typeof DevFeelsRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  PullRequestsIndexRoute: typeof PullRequestsIndexRoute
  PullRequestsOwnerRepoNumberRoute: typeof PullRequestsOwnerRepoNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/feels': {
      id: '/dev/feels'
      path: '/dev/feels'
      fullPath: '/dev/feels'
      preLoaderRoute: typeof DevFeelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests/': {
      id: '/pull-requests/'
      path: '/pull-requests'
      fullPath: '/pull-requests/'
      preLoaderRoute: typeof PullRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$page': {
      id: '/settings/$page'
      path: '/$page'
      fullPath: '/settings/$page'
      preLoaderRoute: typeof SettingsPageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests/$owner/$repo/$number': {
      id: '/pull-requests/$owner/$repo/$number'
      path: '/pull-requests/$owner/$repo/$number'
      fullPath: '/pull-requests/$owner/$repo/$number'
      preLoaderRoute: typeof PullRequestsOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsPageRoute: typeof SettingsPageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsPageRoute: SettingsPageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UsageRoute: UsageRoute,
  BotsBotIdRoute: BotsBotIdRoute,
  DevFeelsRoute: DevFeelsRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  PullRequestsIndexRoute: PullRequestsIndexRoute,
  PullRequestsOwnerRepoNumberRoute: PullRequestsOwnerRepoNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
