import type { Project } from '@jetty/shared/wire'

import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog'
import { useTestProjectContainer } from '@/state/containers'
import { CopyIcon } from '@phosphor-icons/react'
import { useState } from 'react'

function prompt(project: Project) {
  return `Set up this repository for Jetty container threads.

Jetty runs each container thread in a Docker container with an independent Git clone at /workspace, a persistent private home at /home/jetty, and persistent output at /artifacts. Follow-up messages reuse the checkout. Agent CLIs, tools, dev servers, and browser verification run inside the container.

Inspect this repository's development instructions. Create .jetty/container/Dockerfile and .jetty/container.json. Build and tag the image locally for this machine's native architecture. Jetty consumes the image; it does not build it.

Manifest schema:
{
  "version": 1,
  "image": "jetty/project:dev",
  "setup": "repeatable setup command",
  "dev": [{ "name": "web", "command": "foreground dev command binding 0.0.0.0", "port": 5173, "readyPath": "/" }],
  "verify": "finite meaningful verification command",
  "requiredEnv": []
}

Install pinned Linux provider CLIs, Git, project runtimes, and verification tools in the image. Use a non-root user that can write the mounts. Keep credentials out of the image and tracked files. Put machine-specific values in ~/.jetty/projects/${project.id}/container.local.json with optional envFile and copyFiles fields. Do not mount the host home, original checkout, or Docker socket.

Providers: Codex, Claude, Grok. Codex uses a private copy of the host auth.json. Claude requires CLAUDE_CODE_OAUTH_TOKEN generated by the human with claude setup-token; do not run that interactive command. Grok requires XAI_API_KEY. Mark a provider blocked when its credential or Linux CLI is missing.

Test against a fresh clone of the selected committed revision. Prove setup, verification, dev-server readiness, host reachability, ownership, isolation of two instances using the same internal ports, and an edit surviving stop/start. Report the image tag, tested revision, providers, commands, results, and blockers. Finish with the configuration ready for Jetty's Test configuration button.

Project: ${project.path}
Starting revision: HEAD`
}

export function ContainerSetupDialog({
  project,
  open,
  onOpenChange,
  enabled,
}: {
  project: Project | undefined
  open: boolean
  onOpenChange: (open: boolean) => void
  enabled: boolean
}) {
  const test = useTestProjectContainer()
  const [busy, setBusy] = useState(false)
  const [result, setResult] = useState<string>()
  const [copied, setCopied] = useState(false)
  if (!project) return null
  function runTest() {
    if (!project) return
    setBusy(true)
    setResult(undefined)
    test(
      project.id,
      (reply) => {
        setResult(reply.result)
        setBusy(false)
      },
      () => {
        setResult(undefined)
        setBusy(false)
      }
    )
  }
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className='max-h-[85vh] gap-4 overflow-y-auto sm:max-w-2xl'>
        <DialogTitle>Set up containers</DialogTitle>
        <DialogDescription className='sr-only'>
          Container setup prompt and configuration test
        </DialogDescription>
        <pre className='scrollbar-subtle max-h-[50vh] overflow-auto rounded-md bg-muted p-3 text-xs whitespace-pre-wrap text-foreground'>
          {prompt(project)}
        </pre>
        <div className='flex items-center justify-between gap-3'>
          <output className='min-w-0 truncate text-xs text-muted-foreground'>
            {result ?? project.containerResult ?? ''}
          </output>
          <div className='flex shrink-0 gap-2'>
            <Button
              variant='outline'
              size='sm'
              onClick={() => {
                void navigator.clipboard.writeText(prompt(project)).then(() => setCopied(true))
              }}
            >
              <CopyIcon data-icon='inline-start' />
              {copied ? 'Copied' : 'Copy setup prompt'}
            </Button>
            <Button size='sm' disabled={!enabled || busy} onClick={runTest}>
              {busy ? 'Testing…' : 'Test configuration'}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
