import type { Project } from '@jetty/shared/wire'

import { ComposerLoadout } from '@/components/custom/composer_loadout'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog'
import { useCreateThread, useLoadouts, useSendTurn, useThreadLoadout } from '@/state'
import { useContainerSetupStatus, useTestProjectContainer } from '@/state/containers'
import { CopyIcon } from '@phosphor-icons/react'
import { useNavigate } from '@tanstack/react-router'
import { useEffect, useState } from 'react'

import { DisabledTooltip } from './disabled_tooltip'

function prompt(project: Project) {
  return `Set up this repository for Jetty container threads.

Jetty runs each container thread in a Docker container with an independent Git clone at /workspace, a persistent private home at /home/jetty, and persistent output at /artifacts. Follow-up messages reuse the checkout. Agent CLIs, tools, dev servers, and browser verification run inside the container.

Inspect this repository's development instructions. Create .jetty/container/Dockerfile and .jetty/container.json. Build and tag the image locally for this machine's native architecture. Jetty consumes the image; it does not build it.

Manifest schema:
{
  "version": 1,
  "image": "jetty/project:dev",
  "setup": "repeatable setup command",
  "dev": [{ "name": "web", "command": "foreground dev command binding 0.0.0.0", "port": 5173, "readyPath": "/" }],
  "verify": "finite meaningful verification command",
  "requiredEnv": []
}

Install pinned Linux provider CLIs, Git, project runtimes, and verification tools in the image. Use these official Linux installers (run each as the non-root user, then verify command -v and --version):
- Codex: curl -fsSL https://chatgpt.com/codex/install.sh | sh
- Claude: curl -fsSL https://claude.ai/install.sh | bash
- Grok: curl -fsSL https://x.ai/cli/install.sh | bash
Pin the resulting versions in the Dockerfile. Move installed CLI binaries and their support files to /opt or /usr/local/bin: Jetty mounts a private home over /home/jetty, which hides anything the image installs there. Put CLI commands in /usr/local/bin because Jetty runs them through sh -lc, which may reset PATH. Keep CODEX_HOME unset at runtime so Codex finds its private auth under /home/jetty/.codex. Verify command -v and --version for each CLI with an empty bind mount at /home/jetty, host UID, and sh -lc. Use a non-root user that can write the mounts. Keep credentials out of the image and tracked files. Put machine-specific values in ~/.jetty/projects/${project.id}/container.local.json with optional envFile, copyFiles, and homeFiles fields; homeFiles lists paths under the host home, such as ~/.claude/skills, copied into each environment's home. Do not mount the host home, original checkout, or Docker socket.

Providers: Codex, Claude, Grok. Codex uses a private copy of the host auth.json. Claude requires CLAUDE_CODE_OAUTH_TOKEN generated by the human with claude setup-token; do not run that interactive command. Grok requires XAI_API_KEY. Mark a provider blocked when its credential or Linux CLI is missing.

Test against a fresh clone of the selected committed revision. Prove setup, verification, dev-server readiness, host reachability, ownership, isolation of two instances using the same internal ports, and an edit surviving stop/start. Report the image tag, tested revision, providers, commands, results, and blockers. Finish with the configuration ready for Jetty's Test configuration button.

Project: ${project.path}
Starting revision: HEAD`
}

export function ContainerSetupDialog({
  project,
  open,
  onOpenChange,
  enabled,
}: {
  project: Project | undefined
  open: boolean
  onOpenChange: (open: boolean) => void
  enabled: boolean
}) {
  const test = useTestProjectContainer()
  const checkSetup = useContainerSetupStatus()
  const createThread = useCreateThread()
  const sendTurn = useSendTurn()
  const { loadouts, catalog, setLoadouts } = useLoadouts()
  const { loadout, setLoadout } = useThreadLoadout(undefined)
  const navigate = useNavigate()
  const [busy, setBusy] = useState(false)
  const [result, setResult] = useState<string>()
  const [copied, setCopied] = useState(false)
  const [setup, setSetup] = useState<{
    projectId: string
    imageReady: boolean
    capacityError: string | null
  }>()
  useEffect(() => {
    if (!open || !project || !enabled) return
    const check = () =>
      checkSetup(project.id, (result) => setSetup({ projectId: project.id, ...result }))
    check()
    const timer = window.setInterval(check, 5000)
    return () => window.clearInterval(timer)
  }, [checkSetup, enabled, open, project])
  if (!project) return null
  const checked = setup?.projectId === project.id ? setup : undefined
  function runTest() {
    if (!project) return
    setBusy(true)
    setResult(undefined)
    test(
      project.id,
      (reply) => {
        setResult(reply.result)
        setBusy(false)
      },
      () => {
        setResult(undefined)
        setBusy(false)
      }
    )
  }
  const setupReason = !enabled
    ? 'Docker is unavailable'
    : !checked
      ? 'Checking Docker capacity'
      : (checked.capacityError ?? (!loadout ? 'Choose a model first' : undefined))
  const testReason = !enabled
    ? 'Docker is unavailable'
    : (checked?.capacityError ??
      (!checked?.imageReady ? 'Build the manifest image first' : undefined))
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className='max-h-[85vh] gap-4 overflow-y-auto sm:max-w-2xl'>
        <DialogTitle>Set up containers · {project.title}</DialogTitle>
        <DialogDescription className='sr-only'>
          Start a local setup thread, then test the container image
        </DialogDescription>
        <p className='truncate text-xs text-muted-foreground' title={project.path}>
          {project.path}
        </p>
        <details className='text-xs'>
          <summary className='cursor-pointer text-muted-foreground'>Setup prompt</summary>
          <pre className='scrollbar-subtle mt-2 max-h-[40vh] overflow-auto rounded-md bg-muted p-3 whitespace-pre-wrap text-foreground'>
            {prompt(project)}
          </pre>
        </details>
        {checked?.capacityError && (
          <p className='text-xs text-destructive'>{checked.capacityError}</p>
        )}
        <div className='flex items-center gap-2 text-xs text-muted-foreground'>
          <span>Setup model</span>
          <ComposerLoadout
            catalog={catalog}
            loadouts={loadouts}
            value={loadout}
            onChange={setLoadout}
            onReorder={setLoadouts}
            onOpenSettings={() => {
              onOpenChange(false)
              void navigate({ to: '/settings' })
            }}
          />
        </div>
        <div className='flex items-center justify-between gap-3'>
          <output className='min-w-0 truncate text-xs text-muted-foreground'>
            {result ?? project.containerResult ?? ''}
          </output>
          <div className='flex shrink-0 gap-2'>
            <Button
              variant='outline'
              size='sm'
              onClick={() => {
                void navigator.clipboard.writeText(prompt(project)).then(() => setCopied(true))
              }}
            >
              <CopyIcon data-icon='inline-start' />
              {copied ? 'Copied' : 'Copy setup prompt'}
            </Button>
            <DisabledTooltip reason={testReason} wrap='flex'>
              <Button
                variant='outline'
                size='sm'
                disabled={Boolean(testReason) || busy}
                onClick={runTest}
              >
                {busy ? 'Testing…' : 'Test configuration'}
              </Button>
            </DisabledTooltip>
            <DisabledTooltip reason={setupReason} wrap='flex'>
              <Button
                size='sm'
                disabled={Boolean(setupReason)}
                onClick={() => {
                  const id = createThread(project.id, 'local')
                  sendTurn(id, prompt(project), 0, loadout, [])
                  onOpenChange(false)
                  void navigate({ to: '/threads/$threadId', params: { threadId: id } })
                }}
              >
                Start setup thread
              </Button>
            </DisabledTooltip>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
