import {
  AnchorIcon,
  AppWindowIcon,
  ArticleIcon,
  AtomIcon,
  BellIcon,
  BookOpenIcon,
  BracketsAngleIcon,
  BracketsCurlyIcon,
  BrainIcon,
  BriefcaseIcon,
  BrowserIcon,
  BugIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  ChartLineUpIcon,
  ChartPieIcon,
  ChatCircleIcon,
  CloudIcon,
  CodeBlockIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  CpuIcon,
  CreditCardIcon,
  CubeIcon,
  DatabaseIcon,
  DesktopIcon,
  DeviceMobileIcon,
  DiceFiveIcon,
  DnaIcon,
  EnvelopeIcon,
  FileCodeIcon,
  FileTextIcon,
  FilmStripIcon,
  FireIcon,
  FlagIcon,
  FlaskIcon,
  FunctionIcon,
  GameControllerIcon,
  GaugeIcon,
  GearIcon,
  GhostIcon,
  GitBranchIcon,
  GitMergeIcon,
  GlobeIcon,
  GraduationCapIcon,
  GraphIcon,
  HammerIcon,
  HardDrivesIcon,
  HeartIcon,
  HouseIcon,
  ImageIcon,
  KeyIcon,
  KeyboardIcon,
  LaptopIcon,
  LeafIcon,
  LightbulbIcon,
  LightningIcon,
  LinkIcon,
  LockIcon,
  MapPinIcon,
  MegaphoneIcon,
  MusicNoteIcon,
  NotebookIcon,
  PackageIcon,
  PaintBrushIcon,
  PaletteIcon,
  PawPrintIcon,
  PenNibIcon,
  PencilIcon,
  PlanetIcon,
  PlugIcon,
  PuzzlePieceIcon,
  RobotIcon,
  RocketIcon,
  ShapesIcon,
  ShieldCheckIcon,
  ShippingContainerIcon,
  ShoppingCartIcon,
  SparkleIcon,
  StackIcon,
  StarIcon,
  StorefrontIcon,
  SunIcon,
  SwatchesIcon,
  SwordIcon,
  TableIcon,
  TargetIcon,
  TerminalWindowIcon,
  ToolboxIcon,
  TranslateIcon,
  TreeStructureIcon,
  TrophyIcon,
  UsersIcon,
  WalletIcon,
  WrenchIcon,
  type Icon,
} from '@phosphor-icons/react'

export type ProjectIconOption = { name: string; label: string; icon: Icon; keywords: string }

const icons: readonly (readonly [name: string, icon: Icon, keywords: string])[] = [
  ['code', CodeIcon, 'dev programming source'],
  ['code-block', CodeBlockIcon, 'snippet source editor'],
  ['terminal-window', TerminalWindowIcon, 'cli shell console command'],
  ['brackets-curly', BracketsCurlyIcon, 'json object javascript'],
  ['brackets-angle', BracketsAngleIcon, 'html xml markup tag'],
  ['file-code', FileCodeIcon, 'source script'],
  ['function', FunctionIcon, 'math lambda serverless'],
  ['git-branch', GitBranchIcon, 'version control repo'],
  ['git-merge', GitMergeIcon, 'version control pull request'],
  ['bug', BugIcon, 'debug issue testing'],
  ['package', PackageIcon, 'library npm module dependency'],
  ['cube', CubeIcon, '3d model block object'],
  ['puzzle-piece', PuzzlePieceIcon, 'plugin extension addon'],
  ['wrench', WrenchIcon, 'tool fix maintenance'],
  ['gear', GearIcon, 'settings config automation'],
  ['toolbox', ToolboxIcon, 'tools utilities kit'],
  ['hammer', HammerIcon, 'build tool construct'],
  ['globe', GlobeIcon, 'web internet world website'],
  ['browser', BrowserIcon, 'web website frontend'],
  ['app-window', AppWindowIcon, 'desktop application gui'],
  ['link', LinkIcon, 'url chain api integration'],
  ['device-mobile', DeviceMobileIcon, 'phone ios android app'],
  ['desktop', DesktopIcon, 'computer monitor screen'],
  ['laptop', LaptopIcon, 'computer mac notebook'],
  ['keyboard', KeyboardIcon, 'typing input shortcuts'],
  ['database', DatabaseIcon, 'sql storage data db'],
  ['table', TableIcon, 'spreadsheet grid data'],
  ['chart-bar', ChartBarIcon, 'analytics stats data graph'],
  ['chart-line-up', ChartLineUpIcon, 'growth metrics analytics trading'],
  ['chart-pie', ChartPieIcon, 'analytics dashboard stats'],
  ['graph', GraphIcon, 'network nodes knowledge'],
  ['tree-structure', TreeStructureIcon, 'hierarchy workflow pipeline'],
  ['gauge', GaugeIcon, 'performance speed metrics monitoring'],
  ['cloud', CloudIcon, 'hosting aws server infra'],
  ['hard-drives', HardDrivesIcon, 'server storage infra backend'],
  ['cpu', CpuIcon, 'chip hardware processor embedded'],
  ['plug', PlugIcon, 'integration connector power'],
  ['lightning', LightningIcon, 'fast power energy electric'],
  ['shield-check', ShieldCheckIcon, 'security auth protection'],
  ['lock', LockIcon, 'security privacy encryption'],
  ['key', KeyIcon, 'auth secrets password crypto'],
  ['shipping-container', ShippingContainerIcon, 'docker container deploy'],
  ['stack', StackIcon, 'layers monorepo platform'],
  ['chat-circle', ChatCircleIcon, 'message chat bot conversation'],
  ['envelope', EnvelopeIcon, 'email mail newsletter'],
  ['bell', BellIcon, 'notifications alerts'],
  ['megaphone', MegaphoneIcon, 'marketing announce launch'],
  ['users', UsersIcon, 'team social community people'],
  ['paint-brush', PaintBrushIcon, 'design art style'],
  ['palette', PaletteIcon, 'design color theme'],
  ['pen-nib', PenNibIcon, 'design vector illustration'],
  ['swatches', SwatchesIcon, 'design system colors'],
  ['shapes', ShapesIcon, 'design geometry ui'],
  ['image', ImageIcon, 'photo picture media gallery'],
  ['camera', CameraIcon, 'photo capture media'],
  ['film-strip', FilmStripIcon, 'video movie media'],
  ['music-note', MusicNoteIcon, 'audio sound song'],
  ['book-open', BookOpenIcon, 'docs documentation reading guide'],
  ['notebook', NotebookIcon, 'notes journal wiki'],
  ['file-text', FileTextIcon, 'document docs text'],
  ['article', ArticleIcon, 'blog post writing content'],
  ['pencil', PencilIcon, 'edit writing draft'],
  ['translate', TranslateIcon, 'language i18n localization'],
  ['brain', BrainIcon, 'ai ml machine learning mind'],
  ['robot', RobotIcon, 'ai bot agent automation'],
  ['sparkle', SparkleIcon, 'ai magic new shiny'],
  ['atom', AtomIcon, 'science physics react'],
  ['flask', FlaskIcon, 'science experiment lab chemistry'],
  ['dna', DnaIcon, 'biology genetics science'],
  ['game-controller', GameControllerIcon, 'games gaming play'],
  ['dice-five', DiceFiveIcon, 'games random board'],
  ['sword', SwordIcon, 'games rpg fantasy'],
  ['trophy', TrophyIcon, 'games win award competition'],
  ['ghost', GhostIcon, 'games spooky fun'],
  ['shopping-cart', ShoppingCartIcon, 'ecommerce shop store'],
  ['storefront', StorefrontIcon, 'shop store business marketplace'],
  ['credit-card', CreditCardIcon, 'payments billing finance'],
  ['wallet', WalletIcon, 'money finance crypto budget'],
  ['briefcase', BriefcaseIcon, 'work business job'],
  ['calendar', CalendarIcon, 'schedule events dates'],
  ['rocket', RocketIcon, 'launch ship deploy startup'],
  ['house', HouseIcon, 'home personal smart home'],
  ['heart', HeartIcon, 'love health favorite'],
  ['star', StarIcon, 'favorite featured'],
  ['flag', FlagIcon, 'milestone goal feature flags'],
  ['target', TargetIcon, 'goal focus aim'],
  ['map-pin', MapPinIcon, 'location maps geo travel'],
  ['compass', CompassIcon, 'navigation explore travel'],
  ['planet', PlanetIcon, 'space astronomy universe'],
  ['anchor', AnchorIcon, 'boat harbor dock marine'],
  ['leaf', LeafIcon, 'nature green eco plant'],
  ['sun', SunIcon, 'weather light day'],
  ['fire', FireIcon, 'hot flame trending'],
  ['coffee', CoffeeIcon, 'cafe java drink break'],
  ['lightbulb', LightbulbIcon, 'idea innovation experiment'],
  ['graduation-cap', GraduationCapIcon, 'education learning school course'],
  ['paw-print', PawPrintIcon, 'pets animals'],
]

export const projectIcons: readonly ProjectIconOption[] = icons.map(([name, icon, keywords]) => ({
  name,
  label: name.charAt(0).toUpperCase() + name.slice(1).replaceAll('-', ' '),
  icon,
  keywords,
}))

export const projectIconsByName = new Map(projectIcons.map((option) => [option.name, option.icon]))
