import {
  AnchorIcon,
  AppWindowIcon,
  NewspaperIcon,
  AtomIcon,
  BellIcon,
  BookOpenIcon,
  CodeXmlIcon,
  BracesIcon,
  BrainIcon,
  BriefcaseIcon,
  BrowserIcon,
  BugIcon,
  CalendarIcon,
  CameraIcon,
  ChartHistogramIcon,
  ChartLineIcon,
  PieChartIcon,
  MessageCircleIcon,
  CloudIcon,
  SourceCodeSquareIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  CpuIcon,
  CreditCardIcon,
  BoxIcon,
  DatabaseIcon,
  ComputerIcon,
  SmartphoneIcon,
  DiceFaces05Icon,
  DnaIcon,
  MailIcon,
  FileCodeIcon,
  FileTextIcon,
  FilmIcon,
  FlameIcon,
  FlagIcon,
  FlaskConicalIcon,
  FunctionIcon,
  GameController03Icon,
  GaugeIcon,
  Settings01Icon,
  GhostIcon,
  GlobeIcon,
  GraduationCapIcon,
  ChartScatterIcon,
  HammerIcon,
  HardDriveIcon,
  HeartIcon,
  HouseIcon,
  Image01Icon,
  KeyIcon,
  KeyboardIcon,
  LaptopIcon,
  LeafIcon,
  LightbulbIcon,
  FlashIcon,
  Link01Icon,
  LockIcon,
  MapPinIcon,
  MegaphoneIcon,
  MusicIcon,
  NotebookIcon,
  PackageIcon,
  PaintBrush01Icon,
  PaletteIcon,
  PawPrintIcon,
  PenToolIcon,
  PencilIcon,
  OrbitIcon,
  PlugIcon,
  PuzzleIcon,
  Robot01Icon,
  RocketIcon,
  ShapesIcon,
  ShieldCheckIcon,
  ContainerIcon,
  ShoppingCartIcon,
  SparklesIcon,
  LayersIcon,
  StarIcon,
  StoreIcon,
  Sun03Icon,
  SwatchBookIcon,
  SwordIcon,
  TableIcon,
  TargetIcon,
  SquareTerminalIcon,
  ToolboxIcon,
  LanguagesIcon,
  NetworkIcon,
  TrophyIcon,
  UsersIcon,
  WalletIcon,
  WrenchIcon,
  type Icon,
} from '@/components/custom/huge_icons'
import { GitBranchIcon, GitMergeIcon } from '@/components/custom/lucide_icons'

export type ProjectIconOption = { name: string; label: string; icon: Icon; keywords: string }

const icons: readonly (readonly [name: string, icon: Icon, keywords: string])[] = [
  ['code', CodeIcon, 'dev programming source'],
  ['code-block', SourceCodeSquareIcon, 'snippet source editor'],
  ['terminal-window', SquareTerminalIcon, 'cli shell console command'],
  ['brackets-curly', BracesIcon, 'json object javascript'],
  ['brackets-angle', CodeXmlIcon, 'html xml markup tag'],
  ['file-code', FileCodeIcon, 'source script'],
  ['function', FunctionIcon, 'math lambda serverless'],
  ['git-branch', GitBranchIcon, 'version control repo'],
  ['git-merge', GitMergeIcon, 'version control pull request'],
  ['bug', BugIcon, 'debug issue testing'],
  ['package', PackageIcon, 'library npm module dependency'],
  ['cube', BoxIcon, '3d model block object'],
  ['puzzle-piece', PuzzleIcon, 'plugin extension addon'],
  ['wrench', WrenchIcon, 'tool fix maintenance'],
  ['gear', Settings01Icon, 'settings config automation'],
  ['toolbox', ToolboxIcon, 'tools utilities kit'],
  ['hammer', HammerIcon, 'build tool construct'],
  ['globe', GlobeIcon, 'web internet world website'],
  ['browser', BrowserIcon, 'web website frontend'],
  ['app-window', AppWindowIcon, 'desktop application gui'],
  ['link', Link01Icon, 'url chain api integration'],
  ['device-mobile', SmartphoneIcon, 'phone ios android app'],
  ['desktop', ComputerIcon, 'computer monitor screen'],
  ['laptop', LaptopIcon, 'computer mac notebook'],
  ['keyboard', KeyboardIcon, 'typing input shortcuts'],
  ['database', DatabaseIcon, 'sql storage data db'],
  ['table', TableIcon, 'spreadsheet grid data'],
  ['chart-bar', ChartHistogramIcon, 'analytics stats data graph'],
  ['chart-line-up', ChartLineIcon, 'growth metrics analytics trading'],
  ['chart-pie', PieChartIcon, 'analytics dashboard stats'],
  ['graph', ChartScatterIcon, 'network nodes knowledge'],
  ['tree-structure', NetworkIcon, 'hierarchy workflow pipeline'],
  ['gauge', GaugeIcon, 'performance speed metrics monitoring'],
  ['cloud', CloudIcon, 'hosting aws server infra'],
  ['hard-drives', HardDriveIcon, 'server storage infra backend'],
  ['cpu', CpuIcon, 'chip hardware processor embedded'],
  ['plug', PlugIcon, 'integration connector power'],
  ['lightning', FlashIcon, 'fast power energy electric'],
  ['shield-check', ShieldCheckIcon, 'security auth protection'],
  ['lock', LockIcon, 'security privacy encryption'],
  ['key', KeyIcon, 'auth secrets password crypto'],
  ['shipping-container', ContainerIcon, 'docker container deploy'],
  ['stack', LayersIcon, 'layers monorepo platform'],
  ['chat-circle', MessageCircleIcon, 'message chat bot conversation'],
  ['envelope', MailIcon, 'email mail newsletter'],
  ['bell', BellIcon, 'notifications alerts'],
  ['megaphone', MegaphoneIcon, 'marketing announce launch'],
  ['users', UsersIcon, 'team social community people'],
  ['paint-brush', PaintBrush01Icon, 'design art style'],
  ['palette', PaletteIcon, 'design color theme'],
  ['pen-nib', PenToolIcon, 'design vector illustration'],
  ['swatches', SwatchBookIcon, 'design system colors'],
  ['shapes', ShapesIcon, 'design geometry ui'],
  ['image', Image01Icon, 'photo picture media gallery'],
  ['camera', CameraIcon, 'photo capture media'],
  ['film-strip', FilmIcon, 'video movie media'],
  ['music-note', MusicIcon, 'audio sound song'],
  ['book-open', BookOpenIcon, 'docs documentation reading guide'],
  ['notebook', NotebookIcon, 'notes journal wiki'],
  ['file-text', FileTextIcon, 'document docs text'],
  ['article', NewspaperIcon, 'blog post writing content'],
  ['pencil', PencilIcon, 'edit writing draft'],
  ['translate', LanguagesIcon, 'language i18n localization'],
  ['brain', BrainIcon, 'ai ml machine learning mind'],
  ['robot', Robot01Icon, 'ai bot agent automation'],
  ['sparkle', SparklesIcon, 'ai magic new shiny'],
  ['atom', AtomIcon, 'science physics react'],
  ['flask', FlaskConicalIcon, 'science experiment lab chemistry'],
  ['dna', DnaIcon, 'biology genetics science'],
  ['game-controller', GameController03Icon, 'games gaming play'],
  ['dice-five', DiceFaces05Icon, 'games random board'],
  ['sword', SwordIcon, 'games rpg fantasy'],
  ['trophy', TrophyIcon, 'games win award competition'],
  ['ghost', GhostIcon, 'games spooky fun'],
  ['shopping-cart', ShoppingCartIcon, 'ecommerce shop store'],
  ['storefront', StoreIcon, 'shop store business marketplace'],
  ['credit-card', CreditCardIcon, 'payments billing finance'],
  ['wallet', WalletIcon, 'money finance crypto budget'],
  ['briefcase', BriefcaseIcon, 'work business job'],
  ['calendar', CalendarIcon, 'schedule events dates'],
  ['rocket', RocketIcon, 'launch ship deploy startup'],
  ['house', HouseIcon, 'home personal smart home'],
  ['heart', HeartIcon, 'love health favorite'],
  ['star', StarIcon, 'favorite featured'],
  ['flag', FlagIcon, 'milestone goal feature flags'],
  ['target', TargetIcon, 'goal focus aim'],
  ['map-pin', MapPinIcon, 'location maps geo travel'],
  ['compass', CompassIcon, 'navigation explore travel'],
  ['planet', OrbitIcon, 'space astronomy universe'],
  ['anchor', AnchorIcon, 'boat harbor dock marine'],
  ['leaf', LeafIcon, 'nature green eco plant'],
  ['sun', Sun03Icon, 'weather light day'],
  ['fire', FlameIcon, 'hot flame trending'],
  ['coffee', CoffeeIcon, 'cafe java drink break'],
  ['lightbulb', LightbulbIcon, 'idea innovation experiment'],
  ['graduation-cap', GraduationCapIcon, 'education learning school course'],
  ['paw-print', PawPrintIcon, 'pets animals'],
]

export const projectIcons: readonly ProjectIconOption[] = icons.map(([name, icon, keywords]) => ({
  name,
  label: name.charAt(0).toUpperCase() + name.slice(1).replaceAll('-', ' '),
  icon,
  keywords,
}))

export const projectIconsByName = new Map(projectIcons.map((option) => [option.name, option.icon]))
